#Requires -Version 5.1
<#
.SYNOPSIS
    Start the EDI 835 Converter backend and frontend services.

.DESCRIPTION
    Launches the FastAPI backend (uvicorn) and Next.js frontend (npm start)
    as named background jobs, then polls the backend health endpoint until
    it responds HTTP 200 or the attempt limit is reached.

    Ports are read from deploy.env (BACKEND_PORT / FRONTEND_PORT) at the repo
    root  -  copy deploy.env.example to deploy.env and edit those two values to
    change ports on a QA/production host. Nothing else needs editing: CORS on
    the backend and the frontend->backend proxy target are derived from those
    two values automatically at launch time.

    Credentials are NOT stored here. The backend reads its .env file via
    python-dotenv at startup.

.NOTES
    Requires PowerShell 5.1 or later.
    Run stop.ps1 to shut down both services.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 1. Resolve paths
# ---------------------------------------------------------------------------
$root       = Split-Path -Parent $PSScriptRoot   # repo root (parent of scripts\)
$logsDir    = Join-Path $root 'logs'
$backendDir = Join-Path $root 'backend'
$frontendDir= Join-Path $root 'frontend'

# ---------------------------------------------------------------------------
# 2. Read deploy.env for BACKEND_PORT / FRONTEND_PORT
# ---------------------------------------------------------------------------
function Read-EnvFile {
    param([string]$Path)
    $result = @{}
    if (-not (Test-Path -LiteralPath $Path)) { return $result }
    foreach ($line in Get-Content -LiteralPath $Path) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
        $idx = $trimmed.IndexOf('=')
        if ($idx -lt 1) { continue }
        $key = $trimmed.Substring(0, $idx).Trim()
        $val = $trimmed.Substring($idx + 1).Trim()
        $result[$key] = $val
    }
    return $result
}

$deployEnvPath = Join-Path $root 'deploy.env'
$deployEnv     = Read-EnvFile -Path $deployEnvPath

if (-not $deployEnv.ContainsKey('BACKEND_PORT') -or -not $deployEnv.ContainsKey('FRONTEND_PORT')) {
    throw "deploy.env is missing or incomplete at: $deployEnvPath`n" +
          "Copy deploy.env.example to deploy.env and set BACKEND_PORT / FRONTEND_PORT."
}

$BackendPort  = $deployEnv['BACKEND_PORT']
$FrontendPort = $deployEnv['FRONTEND_PORT']

Write-Host "Ports (from deploy.env): backend=$BackendPort  frontend=$FrontendPort"

# ---------------------------------------------------------------------------
# 3. Regenerate web.config (IIS reverse-proxy rules) from deploy.env
#    Assumes IIS runs on the same machine as backend/frontend (localhost).
#    Only needed when hosting behind IIS; harmless otherwise.
# ---------------------------------------------------------------------------
$webConfigPath = Join-Path $root 'web.config'

$webConfigContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by scripts/start.ps1 from deploy.env (BACKEND_PORT / FRONTEND_PORT).
  Do not hand-edit the ports or host below; they get overwritten on the next
  start.ps1 run. To change them, edit deploy.env instead.
-->
<configuration>
  <system.webServer>

    <directoryBrowse enabled="false" />

    <rewrite>
      <rules>

        <!-- API -> FastAPI backend (same machine) -->
        <rule name="EDI API Proxy" stopProcessing="true">
          <match url="^api/(.*)" />
          <action type="Rewrite"
                  url="http://localhost:$BackendPort/api/{R:1}"
                  appendQueryString="true" />
        </rule>

        <!-- Frontend -> Next.js (same machine) -->
        <rule name="EDI Frontend Proxy" stopProcessing="true">
          <match url="^(.*)" />
          <action type="Rewrite"
                  url="http://localhost:$FrontendPort/{R:1}"
                  appendQueryString="true" />
        </rule>

      </rules>
    </rewrite>

  </system.webServer>
</configuration>
"@

Set-Content -LiteralPath $webConfigPath -Value $webConfigContent -Encoding UTF8
Write-Host "web.config regenerated -- API proxy -> localhost:$BackendPort, frontend proxy -> localhost:$FrontendPort"

# ---------------------------------------------------------------------------
# 4. Ensure logs directory exists
# ---------------------------------------------------------------------------
if (-not (Test-Path -LiteralPath $logsDir -PathType Container)) {
    New-Item -ItemType Directory -Path $logsDir | Out-Null
    Write-Host "Created logs directory: $logsDir"
}

$backendLog  = Join-Path $logsDir 'backend.log'
$frontendLog = Join-Path $logsDir 'frontend.log'

# ---------------------------------------------------------------------------
# 5. Start backend job
#    - Changes into the backend directory
#    - Activates the Python virtual environment
#    - CORS_ORIGINS is derived from FRONTEND_PORT so it never needs manual
#      editing in backend/.env when ports change per environment.
#    - Runs uvicorn; stdout+stderr appended to backend.log
# ---------------------------------------------------------------------------
Write-Host "Starting backend service (uvicorn, port $BackendPort)..."

$backendJob = Start-Job -Name 'edi835-backend' -ScriptBlock {
    param([string]$BackendDir, [string]$LogFile, [string]$Port, [string]$FrontendPort)

    Set-Location -LiteralPath $BackendDir

    $activateScript = Join-Path $BackendDir '.venv\Scripts\Activate.ps1'
    if (-not (Test-Path -LiteralPath $activateScript)) {
        throw "Virtual environment not found at: $activateScript"
    }
    & $activateScript

    $env:CORS_ORIGINS = "http://localhost:$FrontendPort,http://127.0.0.1:$FrontendPort"

    uvicorn app.main:app --host 0.0.0.0 --port $Port 2>&1 |
        Out-File -FilePath $LogFile -Append -Encoding utf8

} -ArgumentList $backendDir, $backendLog, $BackendPort, $FrontendPort

Write-Host "Backend  job started  -- ID: $($backendJob.Id)  Name: $($backendJob.Name)"

# ---------------------------------------------------------------------------
# 6. Start frontend job
#    - Changes into the frontend directory
#    - PORT selects the Next.js listen port (package.json no longer hardcodes one)
#    - NEXT_SERVER_API_BASE_URL points the /api/* rewrite at this run's backend port
#    - Runs `npm start` (production server, not dev); stdout+stderr to frontend.log
# ---------------------------------------------------------------------------
Write-Host "Starting frontend service (Next.js, port $FrontendPort)..."

$frontendJob = Start-Job -Name 'edi835-frontend' -ScriptBlock {
    param([string]$FrontendDir, [string]$LogFile, [string]$Port, [string]$BackendPort)

    Set-Location -LiteralPath $FrontendDir

    $env:PORT = $Port
    $env:NEXT_SERVER_API_BASE_URL = "http://localhost:$BackendPort"

    npm start 2>&1 |
        Out-File -FilePath $LogFile -Append -Encoding utf8

} -ArgumentList $frontendDir, $frontendLog, $FrontendPort, $BackendPort

Write-Host "Frontend job started  -- ID: $($frontendJob.Id)  Name: $($frontendJob.Name)"

# ---------------------------------------------------------------------------
# 7. Health-check loop: poll backend root every 2 s, max 60 attempts
# ---------------------------------------------------------------------------
$backendHealthUrl = "http://localhost:$BackendPort/"

Write-Host ""
Write-Host "Polling $backendHealthUrl (max 60 attempts, 2 s interval)..."

$maxAttempts = 60
$attempt     = 0
$healthy     = $false

while ($attempt -lt $maxAttempts) {
    $attempt++

    try {
        $response = Invoke-WebRequest `
            -Uri            $backendHealthUrl `
            -UseBasicParsing `
            -TimeoutSec     2 `
            -ErrorAction    Stop

        if ($response.StatusCode -eq 200) {
            $healthy = $true
            break
        }
    } catch {
        # Backend not accepting connections yet; keep polling
    }

    Start-Sleep -Seconds 2
}

# ---------------------------------------------------------------------------
# 8. Report health outcome
# ---------------------------------------------------------------------------
Write-Host ""
if ($healthy) {
    Write-Host "All services running."
} else {
    Write-Host "WARNING: backend may not be ready"
}

# ---------------------------------------------------------------------------
# 9. Print job / PID summary so the operator knows what to stop
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "--- Service Summary ---"
Write-Host ("Backend  job : ID={0,-4}  Name={1,-20}  State={2}" -f `
    $backendJob.Id, $backendJob.Name, $backendJob.State)
Write-Host ("Frontend job : ID={0,-4}  Name={1,-20}  State={2}" -f `
    $frontendJob.Id, $frontendJob.Name, $frontendJob.State)
Write-Host ""
Write-Host "Backend  log : $backendLog"
Write-Host "Frontend log : $frontendLog"
Write-Host ""
Write-Host "Endpoints    : http://localhost:$BackendPort  (backend)"
Write-Host "               http://localhost:$FrontendPort  (frontend)"
Write-Host ""
Write-Host "To stop all services run: .\scripts\stop.ps1"
